#!/bin/bash
if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
sleep 1
	exit
fi
if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found"
sleep 1
        exit
fi

FILE=~/.ytdlmusic.conf
echo "checking for default save path"
sleep 1
if [ -f "$FILE" ]; then
	change=$(sed -n -e 3p $FILE)
else
echo "~/.ytdlpmusic.conf not found"
sleep 1
read -p "Input directory you want to save music files to (Use full path name ex: /home/YOURUSERNAME/Downloads): " rootdir
cat <<EOF > $FILE
#this file was made to ensure that yt-dlp knows where to save your music
#edit this directory if you with to change it
$rootdir
EOF
change=$(sed -n -e 3p $FILE) 
fi
echo "OK"
cd $change
echo "You will download to:"
pwd
while true
do
	read -r -p "Do you want to add a directory to put your song(s) in? [y/n] " input

	case $input in
	    [yY][eE][sS]|[yY])
			echo "Input directory name" && read dir && mkdir -p $dir && cd $dir; echo "You will now download to:"; pwd
			break
			;;
	    [nN][oO]|[nN])
			sleep 1
			break
	       		;;
	    *)
		echo "Please answer yes or no"
		;;
	esac
done
echo input youtube url.
read url
yt-dlp --extract-audio --audio-format mp3 -i $url

