#!/bin/bash

#check for dependancies
if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
sleep 1s
        exit
fi
if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found"
sleep 1s
        exit
fi

#set default dir
FILE=~/.ytdlvideo.conf
echo "checking for default save path"
sleep 1s
if [ -f "$FILE" ]; then
        change=$(sed -n -e 3p $FILE)
else
echo "~/.ytdlpvideo.conf not found"
sleep 1s
read -p "Input directory you want to save video files to by default (Use full path name ex: /home/YOURUSERNAME/Downloads): " rootdir
cat <<EOF > $FILE
#this file was made to ensure that yt-dlp knows where to save your videos
#edit this directory if you with to change it
$rootdir
EOF
change=$(sed -n -e 3p $FILE)
fi
echo "OK"
sleep 1s
cd $change

#ask for new folder
echo "You are going to download to:"
pwd
while true
do
        read -r -p "Do you want to add a directory to put your vidoe(s) in? [Y/n] " input

        case $input in
            [yY][eE][sS]|[yY])
                        echo "Input directory name" && read dir && mkdir -p $dir && cd $dir; echo "You will now download to:"; pwd
                        break
                        ;;
            [nN][oO]|[nN])
                        sleep 1s
                        break
                        ;;
            *)
                echo "Please answer yes or no"
                ;;
        esac
done

#get url and filename
echo input youtube url.
read url

#select video format
echo 'Choose your option below, to continue:
1 mp4 (same quality as original)
2 mp4 (compressed) will not work with playlists
3 webp (Same quality as original)'
# Function for $errors:
function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
read number && echo "selected"
case $number in
    1)
	yt-dlp --format mp4 $url
	;;
    2)
	filename=$(yt-dlp --restrict-filenames --get-filename $url)
	yt-dlp --restrict-filenames $url
	read -p "Input compression quality 0-51 (0 being no compression, 51 being max compression, 23 being default) " compress
	ffmpeg -i $filename -vcodec libx264 -crf $compress $filename.mp4
	;;
    3)
	yt-dlp --format webm $url
	;;
    *)	echo "invalid option '$number'";;
esac
