#!/bin/bash
#add colors
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
#check version
current="version=1.5"

site1="github.com"
site2="gitlab.com"
site3="git.archuser.org"

# Function to check website availability
check_website() {
    response=$(curl -Is "$1" | head -n 1)
    if [[ $response == *"200"* ]]; then
        echo "Website $1 is available."
        return 0
    else
        echo "Website $1 is not available."
        return 1
    fi
}

# Check availability of websites in order
if check_website "https://$site1"; then
    echo "Checking version using $site1:"
    latest=$(curl -s https://$site1/FireBADnoFire/yt-dlp-utils/-/raw/main/version.txt | sed -n -e 3p)
elif check_website "https://$site2/FireBADnoFire"; then
    echo "Checking version using $site2:"
    latest=$(curl -s https://$site2/FireBADnoFire/yt-dlp-utils/-/raw/main/version.txt | sed -n -e 3p)
elif check_website "https://$site3"; then
    echo "Checking verison using $site3:"
    latest=$(curl -s https://$site3/FireBADnoFire/yt-dlp-utils/-/raw/main/version.txt | sed -n -e 3p)
    else
    echo "Not able to varify if you are up to date. Exiting..."
    exit
fi

latest=$(curl -s https://gitlab.com/FireBADnoFire/yt-dlp-utils/-/raw/main/version.txt | sed -n -e 3p)

#compare version
if [[ "$latest" == "$current" ]]; then
echo -e "${GREEN}You are up to date!${NC}"
else
echo -e "${RED} Your softare is out of date! ${NC}Pull the latest repo to update!"
#remove "exit" below to use this anyway
exit
fi


if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
sleep 1
        exit
fi
if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found"
sleep 1
        exit
fi

if [ $# -eq 0 ];
then
  echo "$0: Missing arguments. Usage: ./music-flags DIR URL"
  exit 1
elif [ $# -gt 2 ];
then
  echo "$0: Too many arguments: $@"
  exit 1
else
echo "Running arguments"
fi

url=$(echo $2)
change=$(echo $1)
mkdir -p $change
cd $change
echo "Music URL: $url"
echo "Directory to save to: $change"
yt-dlp --extract-audio --audio-format mp3 -i $url
