#!/bin/bash
#add colors
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
#check version
current=version=1.2

latest=$(curl -s https://gitlab.com/FireBADnoFire/yt-dlp-utils/-/raw/main/version.txt | sed -n -e 3p)

#compare version
if [[ "$latest" == "$current" ]]; then
echo -e "${GREEN}You are up to date!${NC}"
else
echo -e "${RED} Your softare is out of date! ${NC}Pull the latest repo to update!"
#remove "exit" below to use this anyway
exit
fi


if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
sleep 1
        exit
fi
if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found"
sleep 1
        exit
fi

if [ $# -eq 0 ];
then
  echo "$0: Missing arguments. Usage: ./video-flags DIR URL"
  exit 1
elif [ $# -gt 2 ];
then
  echo "$0: Too many arguments: $@"
  exit 1
else
echo "Running arguments"
fi

url=$(echo $2)
change=$(echo $1)
mkdir -p $change
cd $change
echo "video URL: $url"
echo "Directory to save to: $change"
yt-dlp --format mp4 $url
