#!/bin/bash
#add colors
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

echo "Checking version using github:"
latest=$(curl -s https://codeberg.org/firebadnofire/yt-dlp-utils/raw/branch/main/version.txt | sed -n -e 3p)

#compare version
current="version=1.10"

if [[ "$latest" == "$current" ]]; then
    echo -e "${GREEN}You are up to date!${NC}"
else
    echo -e "${RED}Your software is out of date! ${NC}Pull the latest repo to update!"
    #remove "exit" below to use this anyway
    exit 1
fi

if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
sleep 1
        exit
fi
if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found"
sleep 1
        exit
fi


python3 /usr/bin/gui.py
