#!/bin/bash
#add color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
#check version
current="version=1.9"

    echo "Checking version using github:"
    latest=$(curl -s https://codeberg.org/firebadnofire/yt-dlp-utils/raw/branch/main/version.txt | sed -n -e 3p)

#compare version
if [[ "$latest" == "$current" ]]; then
echo -e "${GREEN}You are up to date!${NC}"
else
echo -e "${RED} Your softare is out of date! ${NC}Pull the latest repo to update!"
#remove "exit" below to use this anyway
exit
fi

#check for dependancies
if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found"
sleep 1
        exit
fi
if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found"
sleep 1
        exit
fi

#set default dir
FILE=~/.config/ytdlputils/ytdlvideo.conf
echo "checking for default save path"
sleep 1
if [ -f "$FILE" ]; then
        change=$(sed -n -e 3p $FILE)
else
echo "~/.config/ytdlputils/ytdlpvideo.conf not found"
sleep 1
read -p "Input directory you want to save video files to by default (Use full path name ex: /home/YOURUSERNAME/Downloads): " rootdir
mkdir -p $rootdir
mkdir -p ~/.config/ytdlputils
cat <<EOF > $FILE
#this file was made to ensure that yt-dlp knows where to save your videos
#edit this directory if you with to change it
$rootdir
EOF
change=$(sed -n -e 3p $FILE)
fi
echo "OK"
sleep 1
cd $change

#ask for new folder
echo "You are going to download to:"
pwd
while true
do
        read -r -p "Do you want to add a directory to put your video(s) in? [Y/n] " input

        case $input in
            [yY][eE][sS]|[yY])
                        echo "Input directory name" && read dir && mkdir -p $dir && cd $dir; echo "You will now download to:"; pwd
                        break
                        ;;
            [nN][oO]|[nN])
                        sleep 1
                        break
                        ;;
            *)
                echo "Please answer yes or no"
                ;;
        esac
done

#get url and filename
echo input youtube url.
read url

#select video format
echo 'Choose your option below, to continue:
1 mp4 (same quality as original)
2 mp4 (compressed) will not work with playlists
3 mkv (same quality as original)'
# Function for $errors:
function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
read number && echo "selected"
case $number in
    1)
	yt-dlp -4 --extract-audio --audio-format mp3 --embed-thumbnail --add-metadata --metadata-from-title "%(artist)s - %(title)s" -i $url
	;;
    2)
	filename=$(yt-dlp -4 --embed-thumbnail --restrict-filenames --get-filename $url)
	yt-dlp -4 --embed-thumbnail --add-metadata --metadata-from-title "%(artist)s - %(title)s" --restrict-filenames $url
	read -p "Input compression quality 0-51 (0 being no compression, 51 being max compression, 23 being default) " compress
	ffmpeg -i $filename -c:v libx264 -crf $compress $filename.mp4
	;;
    3)
	yt-dlp -4 --embed-thumbnail --add-metadata --metadata-from-title "%(artist)s - %(title)s" -i $url
	;;
    *)	echo "invalid option '$number'";;
esac
